use_frameworks!
inhibit_all_warnings!
platform :ios, '13.0'

# Please use 'pod install --repo-update' to ensure you have the latest versions of our SDKs.

target 'AppLovinDemo_oc' do
  pod 'AppLovinSDK'
  pod 'Adjust'
  pod 'OpAdxSdk', '2.8.2'
  pod 'ALMAXOperaSDKAdapter', '2.8.2.0'
end
